channels:
    - default
    - conda-forge

dependencies:
    - nomkl
    - numpy >= 1.9
    - scipy
    - matplotlib
    - h5py
    - pytest
    - jupyter
    - libgcc
    - mock
    - sphinx
    - python=3.7
    - pytest-profiling
    - autopep8
    - requests
    - pip
